name: resume_learning
description: A learning app with resume functionality
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Video Player
  video_player: ^2.8.1
  chewie: ^1.7.4
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Client
  http: ^1.1.2
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true